### ISSUE TITLE
Invalid output ; Stream pipe crashing

### ISSUE THREAD

**Issue by ghost** [micnews/stream-volume#1]
Hello, i know this module is 10 Years old, but i really need it for a project.
When using you're module to get the volume level, the stream pipe will at random interval stop completly from working.
Requiring to stop the pipe and restart it (my bot is doing it when i stop talking)
More infos in the video in attachment.
https://vimeo.com/512032287
(The token in the video has been changed)

**Comment by juliangruber** [comment]
Aaah, I think the module name can be misleading, this is for measuring the total "traffic" or data sent, not the vole of any signal.

**Comment by ghost** [comment]
Oh i see :') thanks anyway

________________________________
De : Julian Gruber <notifications@github.com>
Envoyé : samedi 13 février 2021 22:55
À : micnews/stream-volume <stream-volume@noreply.github.com>
Cc : xPyth <johan-ferrer@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [micnews/stream-volume] Invalid output ; Stream pipe crashing (#1)


Aaah, I think the module name can be misleading, this is for measuring the total "traffic" or data sent, not the vole of any signal.

**Comment by ralphtheninja** [comment]
@juliangruber :wave: I like your long hair!
